FROM maven:3.9.6-amazoncorretto-21 AS build

WORKDIR /app

COPY pom.xml .
COPY common common/
COPY receiver receiver/

RUN mvn clean package -pl :common,:receiver -am -DskipTests --no-transfer-progress

FROM amazoncorretto:21-alpine

WORKDIR /app

COPY --from=build /app/receiver/target/*.jar app.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "app.jar"]